name: MLOps Pipeline

on:
  push:
    branches: [cicd]
  workflow_dispatch: 

env:
  AWS_REGION: us-east-1
  S3_BUCKET: churn-bkt  
  
jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push commits

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use built-in token

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate dataset
      run: python generate_data.py

    - name: Train model
      run: python train.py
